<a href="https://colab.research.google.com/github/Infraking/Financial-Fraud-Detection-System/blob/main/02_Preprocessing_Feature_Engineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Financial Transaction Data Preprocessing and Feature Engineering

### Objective
The objective of this notebook is to preprocess the financial transaction dataset by loading the data, exploring its structure, handling missing values, identifying duplicates, and preparing it for feature engineering and machine learning.

## Step 1: Import Required Libraries

Import the necessary Python libraries for data manipulation and numerical computations.

In [1]:
import pandas as pd
import numpy as np

## Step 2: Extract Dataset

The dataset is provided as a ZIP file. Extract it before loading it into a Pandas DataFrame.

In [8]:
import zipfile

with zipfile.ZipFile("/content/PS_20174392719_1491204439457_log.csv.zip", "r") as zip_ref:
    zip_ref.extractall("/content")

print(os.listdir("/content"))

['.config', 'PS_20174392719_1491204439457_log.csv.zip', 'PS_20174392719_1491204439457_log.csv', '.ipynb_checkpoints', 'sample_data']

## Step 3: Load the Dataset

Read the extracted CSV file using Pandas.

In [10]:
df = pd.read_csv("/content/PS_20174392719_1491204439457_log.csv")

## Step 4: Display First Five Records

View the first few rows to understand the dataset.

In [11]:
df.head()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.0,0.0,0,0
1,1,PAYMENT,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.0,0.0,0,0
2,1,TRANSFER,181.00,C1305486145,181.0,0.00,C553264065,0.0,0.0,1,0
3,1,CASH_OUT,181.00,C840083671,181.0,0.00,C38997010,21182.0,0.0,1,0
4,1,PAYMENT,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.0,0.0,0,0

## Step 5: Dataset Information

Display the number of rows, columns, data types, and missing values.

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6362620 entries, 0 to 6362619
Data columns (total 11 columns):
 #   Column          Dtype
---  ------          -----
 0   step            int64
 1   type            object
 2   amount          float64
 3   nameOrig        object
 4   oldbalanceOrg   float64
 5   newbalanceOrig  float64
 6   nameDest        object
 7   oldbalanceDest  float64
 8   newbalanceDest  float64
 9   isFraud         int64
 10  isFlaggedFraud  int64
dtypes: float64(5), int64(3), object(3)
memory usage: 534.0+ MB

## Step 6: Basic Data Exploration

Check the dataset dimensions, data types, and summary statistics.

In [13]:
df.shape

(6362620, 11)

## Step 7: Check Missing Values

Identify whether any missing values exist in the dataset.

In [14]:
df.isnull().sum()

step              0
type              0
amount            0
nameOrig          0
oldbalanceOrg     0
newbalanceOrig    0
nameDest          0
oldbalanceDest    0
newbalanceDest    0
isFraud           0
isFlaggedFraud    0
dtype: int64

## Step 8: Check Duplicate Records

Verify whether duplicate rows are present in the dataset.

In [15]:
df.duplicated().sum()

np.int64(0)

In [16]:
df = df.drop_duplicates()

In [17]:
df.shape

(6362620, 11)

In [18]:
df.dtypes

step                int64
type               object
amount            float64
nameOrig           object
oldbalanceOrg     float64
newbalanceOrig    float64
nameDest           object
oldbalanceDest    float64
newbalanceDest    float64
isFraud             int64
isFlaggedFraud      int64
dtype: object

In [19]:
df["type"].unique()

array(['PAYMENT', 'TRANSFER', 'CASH_OUT', 'DEBIT', 'CASH_IN'],
      dtype=object)

In [20]:
df["type"].value_counts()

type
CASH_OUT    2237500
PAYMENT     2151495
CASH_IN     1399284
TRANSFER     532909
DEBIT         41432
Name: count, dtype: int64

In [21]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df["type"] = le.fit_transform(df["type"])

df.head()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,3,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.0,0.0,0,0
1,1,3,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.0,0.0,0,0
2,1,4,181.00,C1305486145,181.0,0.00,C553264065,0.0,0.0,1,0
3,1,1,181.00,C840083671,181.0,0.00,C38997010,21182.0,0.0,1,0
4,1,3,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.0,0.0,0,0

In [22]:
df["type"].unique()

array([3, 4, 1, 2, 0])

In [23]:
df["balanceDiffOrig"] = df["oldbalanceOrg"] - df["newbalanceOrig"]

In [24]:
df["balanceDiffDest"] = df["newbalanceDest"] - df["oldbalanceDest"]

In [25]:
df[["balanceDiffOrig", "balanceDiffDest"]].head()

   balanceDiffOrig  balanceDiffDest
0          9839.64              0.0
1          1864.28              0.0
2           181.00              0.0
3           181.00         -21182.0
4         11668.14              0.0

In [26]:
df.to_csv("preprocessed_transactions.csv", index=False)

In [27]:
import os
print(os.listdir("/content"))

['.config', 'PS_20174392719_1491204439457_log.csv.zip', 'PS_20174392719_1491204439457_log.csv', 'preprocessed_transactions.csv', '.ipynb_checkpoints', 'sample_data']

## Conclusion

The dataset has been successfully loaded, explored, and preprocessed. It is now ready for feature engineering and further machine learning tasks.